const fs = require('fs');
const path = require('path');
const { run, get } = require('./db');

const dataDir = path.join(__dirname, '..', '..', 'data');
if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
}

const seedClasses = async () => {
    const classes = [
        {
            id: 1, title: 'React Basic for Beginners', description: 'Dive into the world of React.js. This comprehensive course covers the core concepts of React, including components, props, state, and lifecycle methods. You will learn how to build dynamic and interactive user interfaces using modern React features like Hooks (useState, useEffect) and Context API. By the end of this course, you will be able to create full-fledged single-page applications from scratch.', price: 4040, max_capacity: 300, current_bookings: 213, course_name: 'React Basic for Beginners', image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'John Doe', instructor_image: 'https://i.pravatar.cc/150?u=1', full_description: 'Dive into the world of React.js. This comprehensive course covers the core concepts of React, including components, props, state, and lifecycle methods. You will learn how to build dynamic and interactive user interfaces using modern React features like Hooks (useState, useEffect) and Context API. By the end of this course, you will be able to create full-fledged single-page applications from scratch.', contents: ['ทำความรู้จักกับ React และการติดตั้ง Vite', 'พื้นฐาน Component, JSX และ Props', 'การจัดการ State ด้วย useState', 'การดึงข้อมูลจาก API (useEffect)'], curriculum: [{ chapter: 'Getting Started', lessons: ['Introduction to React', 'Installation and Setup', 'Hello World'] }, { chapter: 'Core Concepts', lessons: ['JSX Explained', 'Components and Props', 'State and Lifecycle'] }, { chapter: 'Advanced Hooks', lessons: ['useMemo and useCallback', 'Custom Hooks'] }], benefits: ['Master React.js fundamentals', 'Build real-world projects', 'Understand modern frontend architecture'], requirements: ['Basic knowledge of HTML and CSS', 'JavaScript ES6+ basics'], class_date: '15 มิถุนายน 2026', students: 150, video_preview_url: 'https://img.youtube.com/vi/sample1/0.jpg'
        },
        {
            id: 2, title: 'Mastering UI Design with Bootstrap', description: 'Master the art of responsive web design with Bootstrap 5. This course teaches you how to leverage the power of the most popular CSS framework to create stunning, mobile-first websites. We will cover the grid system, typography, forms, buttons, and various components like navbars, modals, and carousels. You will also learn how to customize Bootstrap using Sass.', price: 4983, max_capacity: 280, current_bookings: 175, course_name: 'Mastering UI Design with Bootstrap', image: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Jane Smith', instructor_image: 'https://i.pravatar.cc/150?u=2', full_description: 'Master the art of responsive web design with Bootstrap 5. This course teaches you how to leverage the power of the most popular CSS framework to create stunning, mobile-first websites. We will cover the grid system, typography, forms, buttons, and various components like navbars, modals, and carousels. You will also learn how to customize Bootstrap using Sass.', contents: ['ระบบ Grid 12 คอลัมน์', 'การใช้งาน Components หลัก (Card, Navbar, Modal)', 'การปรับแต่งสี (Theming) แบบ Custom', 'การทำเว็บไซต์ให้รองรับมือถือ (Responsive Layout)'], curriculum: [{ chapter: 'Bootstrap Basics', lessons: ['Introduction to Bootstrap', 'The Grid System', 'Layout Utilities'] }, { chapter: 'Components', lessons: ['Buttons and Forms', 'Navigation Bars', 'Cards and Modals'] }], benefits: ['Create responsive designs quickly', 'Use pre-built UI components', 'Customize styles with Sass'], requirements: ['Basic HTML and CSS'], class_date: '20 มิถุนายน 2026', students: 85, video_preview_url: 'https://img.youtube.com/vi/sample2/0.jpg'
        },
        {
            id: 3, title: 'Fullstack Web Developer Bootcamp', description: 'Become a full-stack web developer with this intensive bootcamp. We cover everything from the basics of HTML/CSS to advanced backend development with Node.js and MongoDB. You will learn how to build a complete web application, manage databases, implement authentication, and deploy your projects to the cloud. This course is designed for those who want to start a career in web development.', price: 2474, max_capacity: 196, current_bookings: 124, course_name: 'Fullstack Web Developer Bootcamp', image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Michael Brown', instructor_image: 'https://i.pravatar.cc/150?u=3', full_description: 'Become a full-stack web developer with this intensive bootcamp. We cover everything from the basics of HTML/CSS to advanced backend development with Node.js and MongoDB. You will learn how to build a complete web application, manage databases, implement authentication, and deploy your projects to the cloud. This course is designed for those who want to start a career in web development.', contents: ['ออกแบบ Frontend ด้วย React', 'สร้าง Backend API ด้วย Node.js & Express', 'จัดการฐานข้อมูลด้วย MongoDB', 'การทำเว็บขึ้นระบบจริง (Deployment)'], curriculum: [{ chapter: 'Frontend Foundations', lessons: ['HTML5 and CSS3', 'JavaScript Essentials', 'DOM Manipulation'] }, { chapter: 'Backend Development', lessons: ['Node.js and Express', 'RESTful APIs', 'MongoDB and Mongoose'] }, { chapter: 'Deployment', lessons: ['Heroku and Vercel', 'Git for Production'] }], benefits: ['Learn end-to-end development', 'Build a professional portfolio', 'Understand database management'], requirements: ['No prior experience required, but basic computer skills are helpful'], class_date: '1 กรกฎาคม 2026', students: 320, video_preview_url: 'https://img.youtube.com/vi/sample3/0.jpg'
        },
        {
            id: 4, title: 'สอนใช้งาน Git และ GitHub แบบจับมือทำ', description: 'Learn how to use Git and GitHub to manage your code and collaborate with others. This course takes a \'hand-holding\' approach, guiding you through every step from installing Git to creating pull requests. You will learn about repositories, commits, branching, merging, and resolving conflicts. Essential for every developer working in a team environment.', price: 2082, max_capacity: 260, current_bookings: 198, course_name: 'สอนใช้งาน Git และ GitHub แบบจับมือทำ', image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Sarah Wilson', instructor_image: 'https://i.pravatar.cc/150?u=4', full_description: 'Learn how to use Git and GitHub to manage your code and collaborate with others. This course takes a \'hand-holding\' approach, guiding you through every step from installing Git to creating pull requests. You will learn about repositories, commits, branching, merging, and resolving conflicts. Essential for every developer working in a team environment.', contents: ['คำสั่ง Git พื้นฐาน (add, commit, push)', 'การแยก Branch และการ Merge', 'การแก้ไขปัญหา Code ชนกัน (Merge Conflict)', 'การทำงานร่วมกันเป็นทีมผ่าน GitHub'], curriculum: [{ chapter: 'Git Basics', lessons: ['Installing Git', 'Initializing Repositories', 'Committing Changes'] }, { chapter: 'GitHub Collaboration', lessons: ['Creating GitHub Accounts', 'Pushing to Remote', 'Pull Requests'] }], benefits: ['Master version control', 'Collaborate effectively on projects', 'Build an online presence on GitHub'], requirements: ['Basic understanding of using a computer'], class_date: '10 กรกฎาคม 2026', students: 210, video_preview_url: 'https://img.youtube.com/vi/sample4/0.jpg'
        },
        {
            id: 5, title: 'Python for Data Science', description: 'Unlock the power of data with Python. This course introduces you to the essential tools for data science, including NumPy for numerical computing, Pandas for data manipulation, and Matplotlib/Seaborn for data visualization. You will learn how to clean data, perform exploratory data analysis, and build basic machine learning models using Scikit-Learn.', price: 4744, max_capacity: 365, current_bookings: 326, course_name: 'Python for Data Science', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'David Lee', instructor_image: 'https://i.pravatar.cc/150?u=5', full_description: 'Unlock the power of data with Python. This course introduces you to the essential tools for data science, including NumPy for numerical computing, Pandas for data manipulation, and Matplotlib/Seaborn for data visualization. You will learn how to clean data, perform exploratory data analysis, and build basic machine learning models using Scikit-Learn.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Python', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Python for Data', lessons: ['NumPy Basics', 'Pandas DataFrames', 'Data Cleaning'] }, { chapter: 'Visualization', lessons: ['Matplotlib Plots', 'Seaborn Charts'] }], benefits: ['Analyze large datasets', 'Visualize complex information', 'Kickstart your career in Data Science'], requirements: ['Basic Python programming'], class_date: '4 สิงหาคม 2026', students: 324, video_preview_url: 'https://img.youtube.com/vi/sample5/0.jpg'
        },
        {
            id: 6, title: 'Advanced JavaScript (ES6+)', description: 'This course provides in-depth knowledge and practical skills required to excel in Advanced JavaScript (ES6+). You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 4890, max_capacity: 227, current_bookings: 147, course_name: 'Advanced JavaScript (ES6+)', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Instructor 6', instructor_image: 'https://i.pravatar.cc/150?u=6', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Advanced JavaScript (ES6+). You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ JavaScript', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Advanced JavaScript (ES6+)', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Advanced JavaScript (ES6+)', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '19 สิงหาคม 2026', students: 415, video_preview_url: 'https://img.youtube.com/vi/sample6/0.jpg'
        },
        {
            id: 7, title: 'Node.js Backend Development', description: 'This course provides in-depth knowledge and practical skills required to excel in Node.js Backend Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 331, max_capacity: 491, current_bookings: 401, course_name: 'Node.js Backend Development', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Instructor 7', instructor_image: 'https://i.pravatar.cc/150?u=7', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Node.js Backend Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Backend', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Node.js Backend Development', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Node.js Backend Development', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '21 สิงหาคม 2026', students: 133, video_preview_url: 'https://img.youtube.com/vi/sample7/0.jpg'
        },
        {
            id: 8, title: 'Vue.js Fundamentals', description: 'This course provides in-depth knowledge and practical skills required to excel in Vue.js Fundamentals. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 2980, max_capacity: 452, current_bookings: 286, course_name: 'Vue.js Fundamentals', image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Instructor 8', instructor_image: 'https://i.pravatar.cc/150?u=8', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Vue.js Fundamentals. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Frontend', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Vue.js Fundamentals', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Vue.js Fundamentals', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '20 สิงหาคม 2026', students: 241, video_preview_url: 'https://img.youtube.com/vi/sample8/0.jpg'
        },
        {
            id: 9, title: 'Docker & Kubernetes for Beginners', description: 'This course provides in-depth knowledge and practical skills required to excel in Docker & Kubernetes for Beginners. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 3178, max_capacity: 452, current_bookings: 391, course_name: 'Docker & Kubernetes for Beginners', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Instructor 9', instructor_image: 'https://i.pravatar.cc/150?u=9', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Docker & Kubernetes for Beginners. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ DevOps', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Docker & Kubernetes for Beginners', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Docker & Kubernetes for Beginners', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '19 สิงหาคม 2026', students: 271, video_preview_url: 'https://img.youtube.com/vi/sample9/0.jpg'
        },
        {
            id: 10, title: 'Machine Learning with Python', description: 'This course provides in-depth knowledge and practical skills required to excel in Machine Learning with Python. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 4062, max_capacity: 166, current_bookings: 148, course_name: 'Machine Learning with Python', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop', category: 'Programming', instructor_name: 'Instructor 10', instructor_image: 'https://i.pravatar.cc/150?u=10', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Machine Learning with Python. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ AI', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Machine Learning with Python', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Machine Learning with Python', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '1 สิงหาคม 2026', students: 207, video_preview_url: 'https://img.youtube.com/vi/sample10/0.jpg'
        },
        {
            id: 11, title: 'UI/UX Design Principles', description: 'This course provides in-depth knowledge and practical skills required to excel in UI/UX Design Principles. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 2779, max_capacity: 496, current_bookings: 408, course_name: 'UI/UX Design Principles', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 11', instructor_image: 'https://i.pravatar.cc/150?u=11', full_description: 'This course provides in-depth knowledge and practical skills required to excel in UI/UX Design Principles. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Design', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of UI/UX Design Principles', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master UI/UX Design Principles', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '16 สิงหาคม 2026', students: 125, video_preview_url: 'https://img.youtube.com/vi/sample11/0.jpg'
        },
        {
            id: 12, title: 'Mobile App Dev with Flutter', description: 'This course provides in-depth knowledge and practical skills required to excel in Mobile App Dev with Flutter. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 843, max_capacity: 126, current_bookings: 108, course_name: 'Mobile App Dev with Flutter', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 12', instructor_image: 'https://i.pravatar.cc/150?u=12', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Mobile App Dev with Flutter. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Mobile', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Mobile App Dev with Flutter', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Mobile App Dev with Flutter', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '9 สิงหาคม 2026', students: 383, video_preview_url: 'https://img.youtube.com/vi/sample12/0.jpg'
        },
        {
            id: 13, title: 'Swift for iOS Development', description: 'This course provides in-depth knowledge and practical skills required to excel in Swift for iOS Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 4670, max_capacity: 430, current_bookings: 272, course_name: 'Swift for iOS Development', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 13', instructor_image: 'https://i.pravatar.cc/150?u=13', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Swift for iOS Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Mobile', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Swift for iOS Development', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Swift for iOS Development', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '1 สิงหาคม 2026', students: 283, video_preview_url: 'https://img.youtube.com/vi/sample13/0.jpg'
        },
        {
            id: 14, title: 'Android App Dev with Kotlin', description: 'This course provides in-depth knowledge and practical skills required to excel in Android App Dev with Kotlin. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 2249, max_capacity: 293, current_bookings: 237, course_name: 'Android App Dev with Kotlin', image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 14', instructor_image: 'https://i.pravatar.cc/150?u=14', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Android App Dev with Kotlin. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Mobile', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Android App Dev with Kotlin', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Android App Dev with Kotlin', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '14 สิงหาคม 2026', students: 139, video_preview_url: 'https://img.youtube.com/vi/sample14/0.jpg'
        },
        {
            id: 15, title: 'Cyber Security Essentials', description: 'This course provides in-depth knowledge and practical skills required to excel in Cyber Security Essentials. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1693, max_capacity: 202, current_bookings: 121, course_name: 'Cyber Security Essentials', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 15', instructor_image: 'https://i.pravatar.cc/150?u=15', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Cyber Security Essentials. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Security', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Cyber Security Essentials', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Cyber Security Essentials', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '23 สิงหาคม 2026', students: 295, video_preview_url: 'https://img.youtube.com/vi/sample15/0.jpg'
        },
        {
            id: 16, title: 'AWS Cloud Practitioner', description: 'This course provides in-depth knowledge and practical skills required to excel in AWS Cloud Practitioner. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 3365, max_capacity: 396, current_bookings: 268, course_name: 'AWS Cloud Practitioner', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 16', instructor_image: 'https://i.pravatar.cc/150?u=16', full_description: 'This course provides in-depth knowledge and practical skills required to excel in AWS Cloud Practitioner. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Cloud', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of AWS Cloud Practitioner', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master AWS Cloud Practitioner', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '5 สิงหาคม 2026', students: 341, video_preview_url: 'https://img.youtube.com/vi/sample16/0.jpg'
        },
        {
            id: 17, title: 'Database Management with PostgreSQL', description: 'This course provides in-depth knowledge and practical skills required to excel in Database Management with PostgreSQL. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 4164, max_capacity: 217, current_bookings: 159, course_name: 'Database Management with PostgreSQL', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 17', instructor_image: 'https://i.pravatar.cc/150?u=17', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Database Management with PostgreSQL. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Database', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Database Management with PostgreSQL', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Database Management with PostgreSQL', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '12 สิงหาคม 2026', students: 65, video_preview_url: 'https://img.youtube.com/vi/sample17/0.jpg'
        },
        {
            id: 18, title: 'GraphQL API Development', description: 'This course provides in-depth knowledge and practical skills required to excel in GraphQL API Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 710, max_capacity: 86, current_bookings: 67, course_name: 'GraphQL API Development', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 18', instructor_image: 'https://i.pravatar.cc/150?u=18', full_description: 'This course provides in-depth knowledge and practical skills required to excel in GraphQL API Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Backend', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of GraphQL API Development', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master GraphQL API Development', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '12 สิงหาคม 2026', students: 109, video_preview_url: 'https://img.youtube.com/vi/sample18/0.jpg'
        },
        {
            id: 19, title: 'TypeScript in Depth', description: 'This course provides in-depth knowledge and practical skills required to excel in TypeScript in Depth. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 851, max_capacity: 349, current_bookings: 274, course_name: 'TypeScript in Depth', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 19', instructor_image: 'https://i.pravatar.cc/150?u=19', full_description: 'This course provides in-depth knowledge and practical skills required to excel in TypeScript in Depth. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ JavaScript', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of TypeScript in Depth', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master TypeScript in Depth', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '27 สิงหาคม 2026', students: 55, video_preview_url: 'https://img.youtube.com/vi/sample19/0.jpg'
        },
        {
            id: 20, title: 'Next.js - The React Framework', description: 'This course provides in-depth knowledge and practical skills required to excel in Next.js - The React Framework. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 4478, max_capacity: 299, current_bookings: 264, course_name: 'Next.js - The React Framework', image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop', category: 'Design', instructor_name: 'Instructor 20', instructor_image: 'https://i.pravatar.cc/150?u=20', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Next.js - The React Framework. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Frontend', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Next.js - The React Framework', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Next.js - The React Framework', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '13 สิงหาคม 2026', students: 143, video_preview_url: 'https://img.youtube.com/vi/sample20/0.jpg'
        },
        {
            id: 21, title: 'PHP & Laravel Mastery', description: 'This course provides in-depth knowledge and practical skills required to excel in PHP & Laravel Mastery. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1748, max_capacity: 326, current_bookings: 249, course_name: 'PHP & Laravel Mastery', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 21', instructor_image: 'https://i.pravatar.cc/150?u=21', full_description: 'This course provides in-depth knowledge and practical skills required to excel in PHP & Laravel Mastery. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Backend', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of PHP & Laravel Mastery', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master PHP & Laravel Mastery', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '15 สิงหาคม 2026', students: 387, video_preview_url: 'https://img.youtube.com/vi/sample21/0.jpg'
        },
        {
            id: 22, title: 'Java Programming for Beginners', description: 'This course provides in-depth knowledge and practical skills required to excel in Java Programming for Beginners. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 499, max_capacity: 492, current_bookings: 400, course_name: 'Java Programming for Beginners', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 22', instructor_image: 'https://i.pravatar.cc/150?u=22', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Java Programming for Beginners. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Programming', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Java Programming for Beginners', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Java Programming for Beginners', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '18 สิงหาคม 2026', students: 99, video_preview_url: 'https://img.youtube.com/vi/sample22/0.jpg'
        },
        {
            id: 23, title: 'C# and .NET Core Development', description: 'This course provides in-depth knowledge and practical skills required to excel in C# and .NET Core Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 2399, max_capacity: 151, current_bookings: 118, course_name: 'C# and .NET Core Development', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 23', instructor_image: 'https://i.pravatar.cc/150?u=23', full_description: 'This course provides in-depth knowledge and practical skills required to excel in C# and .NET Core Development. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Programming', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of C# and .NET Core Development', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master C# and .NET Core Development', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '15 สิงหาคม 2026', students: 114, video_preview_url: 'https://img.youtube.com/vi/sample23/0.jpg'
        },
        {
            id: 24, title: 'Go Programming Language', description: 'This course provides in-depth knowledge and practical skills required to excel in Go Programming Language. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 3700, max_capacity: 91, current_bookings: 71, course_name: 'Go Programming Language', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 24', instructor_image: 'https://i.pravatar.cc/150?u=24', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Go Programming Language. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Programming', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Go Programming Language', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Go Programming Language', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '2 สิงหาคม 2026', students: 393, video_preview_url: 'https://img.youtube.com/vi/sample24/0.jpg'
        },
        {
            id: 25, title: 'Data Visualization with Tableau', description: 'This course provides in-depth knowledge and practical skills required to excel in Data Visualization with Tableau. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1577, max_capacity: 165, current_bookings: 132, course_name: 'Data Visualization with Tableau', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 25', instructor_image: 'https://i.pravatar.cc/150?u=25', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Data Visualization with Tableau. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Data', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Data Visualization with Tableau', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Data Visualization with Tableau', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '21 สิงหาคม 2026', students: 230, video_preview_url: 'https://img.youtube.com/vi/sample25/0.jpg'
        },
        {
            id: 26, title: 'Deep Learning with TensorFlow', description: 'This course provides in-depth knowledge and practical skills required to excel in Deep Learning with TensorFlow. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 2885, max_capacity: 201, current_bookings: 169, course_name: 'Deep Learning with TensorFlow', image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 26', instructor_image: 'https://i.pravatar.cc/150?u=26', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Deep Learning with TensorFlow. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ AI', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Deep Learning with TensorFlow', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Deep Learning with TensorFlow', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '23 สิงหาคม 2026', students: 71, video_preview_url: 'https://img.youtube.com/vi/sample26/0.jpg'
        },
        {
            id: 27, title: 'Natural Language Processing (NLP)', description: 'This course provides in-depth knowledge and practical skills required to excel in Natural Language Processing (NLP). You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 3041, max_capacity: 148, current_bookings: 91, course_name: 'Natural Language Processing (NLP)', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 27', instructor_image: 'https://i.pravatar.cc/150?u=27', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Natural Language Processing (NLP). You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ AI', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Natural Language Processing (NLP)', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Natural Language Processing (NLP)', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '28 สิงหาคม 2026', students: 318, video_preview_url: 'https://img.youtube.com/vi/sample27/0.jpg'
        },
        {
            id: 28, title: 'Blockchain & Smart Contracts', description: 'This course provides in-depth knowledge and practical skills required to excel in Blockchain & Smart Contracts. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 512, max_capacity: 235, current_bookings: 143, course_name: 'Blockchain & Smart Contracts', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 28', instructor_image: 'https://i.pravatar.cc/150?u=28', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Blockchain & Smart Contracts. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Web3', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Blockchain & Smart Contracts', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Blockchain & Smart Contracts', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '6 สิงหาคม 2026', students: 265, video_preview_url: 'https://img.youtube.com/vi/sample28/0.jpg'
        },
        {
            id: 29, title: 'Game Development with Unity', description: 'This course provides in-depth knowledge and practical skills required to excel in Game Development with Unity. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1595, max_capacity: 327, current_bookings: 221, course_name: 'Game Development with Unity', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 29', instructor_image: 'https://i.pravatar.cc/150?u=29', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Game Development with Unity. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Game', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Game Development with Unity', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Game Development with Unity', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '22 สิงหาคม 2026', students: 134, video_preview_url: 'https://img.youtube.com/vi/sample29/0.jpg'
        },
        {
            id: 30, title: 'SEO & Digital Marketing for Devs', description: 'This course provides in-depth knowledge and practical skills required to excel in SEO & Digital Marketing for Devs. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1927, max_capacity: 247, current_bookings: 211, course_name: 'SEO & Digital Marketing for Devs', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', category: 'Marketing', instructor_name: 'Instructor 30', instructor_image: 'https://i.pravatar.cc/150?u=30', full_description: 'This course provides in-depth knowledge and practical skills required to excel in SEO & Digital Marketing for Devs. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Marketing', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of SEO & Digital Marketing for Devs', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master SEO & Digital Marketing for Devs', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '27 สิงหาคม 2026', students: 424, video_preview_url: 'https://img.youtube.com/vi/sample30/0.jpg'
        },
        {
            id: 31, title: 'Microservices Architecture', description: 'This course provides in-depth knowledge and practical skills required to excel in Microservices Architecture. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1058, max_capacity: 447, current_bookings: 305, course_name: 'Microservices Architecture', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 31', instructor_image: 'https://i.pravatar.cc/150?u=31', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Microservices Architecture. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Architecture', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Microservices Architecture', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Microservices Architecture', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '12 สิงหาคม 2026', students: 438, video_preview_url: 'https://img.youtube.com/vi/sample31/0.jpg'
        },
        {
            id: 32, title: 'Testing & Quality Assurance', description: 'This course provides in-depth knowledge and practical skills required to excel in Testing & Quality Assurance. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 226, max_capacity: 422, current_bookings: 275, course_name: 'Testing & Quality Assurance', image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 32', instructor_image: 'https://i.pravatar.cc/150?u=32', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Testing & Quality Assurance. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Testing', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Testing & Quality Assurance', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Testing & Quality Assurance', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '23 สิงหาคม 2026', students: 142, video_preview_url: 'https://img.youtube.com/vi/sample32/0.jpg'
        },
        {
            id: 33, title: 'Figma for Web Designers', description: 'This course provides in-depth knowledge and practical skills required to excel in Figma for Web Designers. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 1472, max_capacity: 97, current_bookings: 72, course_name: 'Figma for Web Designers', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 33', instructor_image: 'https://i.pravatar.cc/150?u=33', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Figma for Web Designers. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Design', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Figma for Web Designers', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Figma for Web Designers', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '19 สิงหาคม 2026', students: 219, video_preview_url: 'https://img.youtube.com/vi/sample33/0.jpg'
        },
        {
            id: 34, title: 'Linux System Administration', description: 'This course provides in-depth knowledge and practical skills required to excel in Linux System Administration. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 993, max_capacity: 381, current_bookings: 296, course_name: 'Linux System Administration', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 34', instructor_image: 'https://i.pravatar.cc/150?u=34', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Linux System Administration. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ System', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Linux System Administration', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Linux System Administration', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '10 สิงหาคม 2026', students: 374, video_preview_url: 'https://img.youtube.com/vi/sample34/0.jpg'
        },
        {
            id: 35, title: 'Redis for Real-time Apps', description: 'This course provides in-depth knowledge and practical skills required to excel in Redis for Real-time Apps. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 3159, max_capacity: 54, current_bookings: 33, course_name: 'Redis for Real-time Apps', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 35', instructor_image: 'https://i.pravatar.cc/150?u=35', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Redis for Real-time Apps. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Database', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Redis for Real-time Apps', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Redis for Real-time Apps', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '27 สิงหาคม 2026', students: 330, video_preview_url: 'https://img.youtube.com/vi/sample35/0.jpg'
        },
        {
            id: 36, title: 'Rust Programming Mastery', description: 'This course provides in-depth knowledge and practical skills required to excel in Rust Programming Mastery. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 650, max_capacity: 70, current_bookings: 59, course_name: 'Rust Programming Mastery', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 36', instructor_image: 'https://i.pravatar.cc/150?u=36', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Rust Programming Mastery. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Programming', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Rust Programming Mastery', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Rust Programming Mastery', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '13 สิงหาคม 2026', students: 70, video_preview_url: 'https://img.youtube.com/vi/sample36/0.jpg'
        },
        {
            id: 37, title: 'Django Web Framework', description: 'This course provides in-depth knowledge and practical skills required to excel in Django Web Framework. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 850, max_capacity: 126, current_bookings: 93, course_name: 'Django Web Framework', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 37', instructor_image: 'https://i.pravatar.cc/150?u=37', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Django Web Framework. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Backend', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Django Web Framework', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Django Web Framework', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '25 สิงหาคม 2026', students: 59, video_preview_url: 'https://img.youtube.com/vi/sample37/0.jpg'
        },
        {
            id: 38, title: 'Excel for Data Analysts', description: 'This course provides in-depth knowledge and practical skills required to excel in Excel for Data Analysts. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 524, max_capacity: 309, current_bookings: 256, course_name: 'Excel for Data Analysts', image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 38', instructor_image: 'https://i.pravatar.cc/150?u=38', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Excel for Data Analysts. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Data', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Excel for Data Analysts', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Excel for Data Analysts', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '11 สิงหาคม 2026', students: 345, video_preview_url: 'https://img.youtube.com/vi/sample38/0.jpg'
        },
        {
            id: 39, title: 'Power BI Professional', description: 'This course provides in-depth knowledge and practical skills required to excel in Power BI Professional. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 2534, max_capacity: 55, current_bookings: 37, course_name: 'Power BI Professional', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 39', instructor_image: 'https://i.pravatar.cc/150?u=39', full_description: 'This course provides in-depth knowledge and practical skills required to excel in Power BI Professional. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ Data', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of Power BI Professional', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master Power BI Professional', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '6 สิงหาคม 2026', students: 425, video_preview_url: 'https://img.youtube.com/vi/sample39/0.jpg'
        },
        {
            id: 40, title: 'DevOps CI/CD Pipelines', description: 'This course provides in-depth knowledge and practical skills required to excel in DevOps CI/CD Pipelines. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', price: 3123, max_capacity: 166, current_bookings: 131, course_name: 'DevOps CI/CD Pipelines', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop', category: 'Data Science', instructor_name: 'Instructor 40', instructor_image: 'https://i.pravatar.cc/150?u=40', full_description: 'This course provides in-depth knowledge and practical skills required to excel in DevOps CI/CD Pipelines. You will learn through hands-on projects and expert guidance. Covered topics include advanced techniques, best practices, and real-world applications.', contents: ['แนะนำเบื้องต้นเกี่ยวกับ DevOps', 'การตั้งค่าสภาพแวดล้อมและเครื่องมือ', 'Workshop ภาคปฏิบัติ: สร้างโปรเจกต์จริง', 'สรุปเนื้อหาและแนวทางการต่อยอด'], curriculum: [{ chapter: 'Introduction', lessons: ['Overview of DevOps CI/CD Pipelines', 'Key Concepts'] }, { chapter: 'Core Modules', lessons: ['In-depth Analysis', 'Practical Workshop'] }, { chapter: 'Conclusion', lessons: ['Advanced Topics', 'Final Project'] }], benefits: ['Master DevOps CI/CD Pipelines', 'Gain practical experience', 'Certificate of completion'], requirements: ['Basic understanding of the subject', 'Internet access'], class_date: '27 สิงหาคม 2026', students: 327, video_preview_url: 'https://img.youtube.com/vi/sample40/0.jpg'
        }
    ];

    for (const item of classes) {
        await run(
            'INSERT INTO Classes (id, title, description, price, max_capacity, current_bookings, course_name, image, category, instructor_name, instructor_image, full_description, contents, curriculum, benefits, requirements, class_date, students, video_preview_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [item.id, item.title, item.description, item.price, item.max_capacity, item.current_bookings, item.course_name, item.image, item.category, item.instructor_name, item.instructor_image, item.full_description, JSON.stringify(item.contents), JSON.stringify(item.curriculum), JSON.stringify(item.benefits), JSON.stringify(item.requirements), item.class_date, item.students, item.video_preview_url]
        );
    }
};

const init = async () => {
    try {
        await run('BEGIN TRANSACTION', []);

        await run(
            'CREATE TABLE IF NOT EXISTS Users (\
                id INTEGER PRIMARY KEY AUTOINCREMENT,\
                name TEXT NOT NULL,\
                email TEXT NOT NULL UNIQUE,\
                password_hash TEXT NOT NULL,\
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\
            )',
            []
        );

        await run('DROP TABLE IF EXISTS Bookings', []);
        await run('DROP TABLE IF EXISTS Classes', []);

        await run(
            'CREATE TABLE IF NOT EXISTS Classes (\
                id INTEGER PRIMARY KEY AUTOINCREMENT,\
                title TEXT NOT NULL,\
                description TEXT NOT NULL,\
                price INTEGER NOT NULL,\
                max_capacity INTEGER NOT NULL,\
                current_bookings INTEGER NOT NULL DEFAULT 0,\
                course_name TEXT NOT NULL DEFAULT "",\
                image TEXT NOT NULL DEFAULT "",\
                category TEXT NOT NULL DEFAULT "",\
                instructor_name TEXT NOT NULL DEFAULT "",\
                instructor_image TEXT NOT NULL DEFAULT "",\
                full_description TEXT NOT NULL DEFAULT "",\
                contents TEXT NOT NULL DEFAULT "[]",\
                curriculum TEXT NOT NULL DEFAULT "[]",\
                benefits TEXT NOT NULL DEFAULT "[]",\
                requirements TEXT NOT NULL DEFAULT "[]",\
                class_date TEXT NOT NULL DEFAULT "",\
                students INTEGER NOT NULL DEFAULT 0,\
                video_preview_url TEXT NOT NULL DEFAULT ""\
            )',
            []
        );

        await run(
            'CREATE TABLE IF NOT EXISTS Bookings (\
                id INTEGER PRIMARY KEY AUTOINCREMENT,\
                user_id INTEGER NOT NULL,\
                class_id INTEGER NOT NULL,\
                booked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\
                FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE,\
                FOREIGN KEY (class_id) REFERENCES Classes (id) ON DELETE CASCADE\
            )',
            []
        );

        await seedClasses();

        await run('COMMIT', []);
        console.log('Database initialized successfully.');
    } catch (error) {
        await run('ROLLBACK', []);
        console.error('Database initialization failed:', error);
        process.exitCode = 1;
    }
};

init();
